### ISSUE TITLE
There should be a public API that allows to render in a hash.

### ISSUE THREAD

**Issue by vasilakisfil** [jsonapi-rb/jsonapi-serializable#55]
At the moment it seems render returns only a String since it uses to_json. There should be a as_json equivalent publicly accessible.

https://github.com/jsonapi-rb/jsonapi-serializable/blob/master/lib/jsonapi/serializable/renderer.rb#L22

**Comment by beauby** [comment]
Hi @vasilakisfil – you are right. I've had that under my radar for a while but somehow forgot about it. As `jsonapi-serializable` does not depend on ActiveSupport, there would be no `#as_json`, but the returned hash would be what one would expect from `#as_json`.
So, basically it's just a matter of removing `.to_json` [here](https://github.com/jsonapi-rb/jsonapi-serializable/blob/master/lib/jsonapi/serializable/renderer.rb#L22) and [here](https://github.com/jsonapi-rb/jsonapi-serializable/blob/master/lib/jsonapi/serializable/renderer.rb#L62). Feel free to open a PR if you have the file open in your text editor already, otherwise I'll do it myself over the weekend.

**Comment by Aryk** [comment]
@beauby was this merged into rubygems version?
