### ISSUE TITLE
Require JSONAPI Request with Relationship without Include

### ISSUE THREAD

**Issue by fredmaremyob** [jsonapi-rb/jsonapi-serializable#90]
Hi

Would it be possible to render a JSON request with a relationship without having to specify the include option. When I specify only the relationship I get a "meta"=>{"included"=>false}} as part of the JSON output

Thank you very much

**Comment by beauby** [comment]
Hi @fredmaremyob – this is by design. Linkage data, by default, is only loaded when the corresponding relationship is included. Note that if you had a link defined for that relationship, the "meta included false" would be replaced with that link.
If you do want to include linkage data regardless of whether the relationship was included, then you can add `linkage always: true` in your relationship definition.

**Comment by fredmaremyob** [comment]
Thank you for the quick response.
Would it be possible to render the following request? Without the include 

POST /resources
{  
   "data":{  
      "type":"resource",
      "id":"id",
      "relationships":{  
         "resourceType":{  
            "data":{  
               "type":"resourceType",
               "id":"id"
            }
         }
      }
   }
}

**Comment by beauby** [comment]
Yes, just do:
```ruby
has_one :foo do
  linkage always: true
end

**Comment by fredmaremyob** [comment]
Thank you so much. Works perfectly!
